---
- hosts: webserver
  become: true
  tasks:
    - name: Install Nginx Server
      yum: name=tree update_cache=yes state=present
      notify:
        - Start nginx Server
  handlers:
    - name: Start nginx Server
      service:
          name=tree
          state=restarted
...
