---
- hosts: webserver
  become: true
  tasks:
    - name: Install Nginx Server
      yum: name=tomcat9 update_cache=yes state=present
      notify:
        - Start nginx Server
  handlers:
    - name: Start nginx Server
      service:
          name=tomcat9
          state=restarted
...
